services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ../saved:/app/saved
      - ../data:/app/data
    environment:
      - DL_CONFIG=full_ts_approach
