model:
  hidden_size: 128
  dropout: 0.01
  embedder:
    t: 38
    mode: ts_full
    cat_emb_dim: 8
  layer:
    attention:
      depth: 4
      n_heads: 4
    ffn:
      d_ff: 512
  L: 4
  pooler: one_token
  out_features: 3
dataset:
  name: selected_leagues_one_line
  none_fill: zero
  data:
    target_column: match_result
    season_column: season
    val_season: 2024-2025
    depth: ${model.layer.attention.depth}
    t: ${model.embedder.t}
    ts: True
    cat_columns:
      - league_code
      - referee
      - team
    save_columns:
      - ftg
      - s
      - st
      - f
      - c
      - y
      - r
      - ht_w
      - ht_d
      - ht_l
train:
  kfold_steps: 1
  batch_size: 256
  n_epochs: 4
optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4
  weight_decay: 1e-2
scheduler:
  _target_: torch.optim.lr_scheduler.LinearLR
  start_factor: 1.0
  end_factor: 0.0001
criterion:
  _target_: torch.nn.CrossEntropyLoss
  label_smoothing: 0.1
logger:
  project_name: "socer_project"
  entity: null
  run_name: "run_ts-full_lr3e-4_h128_l4_t38_nh4_d4_4ep_wd1e-2_d001_clip_ls"
  mode: "online"
  loss_names: ["loss"]
