model:
  hidden_size: 512
  dropout: 0.1
  embedder:
    t: 1
    mode: stats
    cat_emb_dim: 8
  layer:
    attention:
      depth: 4
      n_heads: 8
    ffn:
      d_ff: 2048
  L: 8
  pooler: one_token
  out_features: 3
dataset:
  name: selected_leagues_one_line
  none_fill: zero
  data:
    target_column: match_result
    season_column: season
    val_season: 2024-2025
    depth: ${model.layer.attention.depth}
    t: ${model.embedder.t}
    cat_columns:
      - league_code
      - referee
      - team
    ignore_columns_prefix: enemy_
    igonre_columns:
      - ftg
      - enemy_ftg
      - s
      - st
      - f
      - c
      - y
      - r
      - enemy_s
      - enemy_st
      - enemy_f
      - enemy_c
      - enemy_y
      - enemy_r
      - ht_w
      - ht_d
      - ht_l
      - date
      - season
      - enemy_team
train:
  kfold_steps: 5
  batch_size: 256
  n_epochs: 10
optimizer:
  _target_: torch.optim.Adam
  lr: 3e-3
  weight_decay: 1e-3
scheduler:
  _target_: torch.optim.lr_scheduler.LinearLR
  start_factor: 1.0
  end_factor: 0.01
criterion:
  _target_: torch.nn.CrossEntropyLoss
logger:
  project_name: "socer_project"
  entity: null
  group: "stats_hpo_nik"
  job_type: "hpo"
  tags: ["stats", "hpo"]
  run_name: "stats_reg_combo_5_fold"
  mode: "online"
  loss_names: ["loss"]